name: Run unittests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "**" ]
    tags: 
      - "*"


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.11'

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Install dependencies
              run: |
                python -m venv .venv
                source .venv/bin/activate
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install maturin

            - name: Build Rust extension
              run: |
                source .venv/bin/activate
                maturin develop --release

            - name: Run tests
              run: |
                source .venv/bin/activate
                pytest tests/