# SPDX-License-Identifier: GPL-3.0-only AND LicenseRef-AI-Training-Prohibited
# Copyright (c) Jako Rostami 2024-present
# Project: expectation
#
# Licensed under GPL-3.0 with additional restrictions per Section 7(b).
# Use of this code for AI/ML model training is strictly prohibited.
# See LICENSE for full terms.

"""
Upper-expectation nulls on finite outcome spaces, with certified e-variables.

Based on these papers:

Game-Theoretic Foundations for Probability and Finance, G. Shafer, V. Vovk (2019), Wiley
    - Chapter 6 (upper expectations; a convex set of forecasts as Forecaster's announcement)

Hypothesis testing with e-values, A. Ramdas, R. Wang (2025) - https://arxiv.org/pdf/2410.23614
    - Definition 2.1 (e-variable for a composite null: sup_{P in P} E_P[E] <= 1)

The numeraire e-variable and reverse information projection, M. Larsson, A. Ramdas,
J. Ruf (2025), Annals of Statistics - https://arxiv.org/pdf/2402.18810
    - Definition 2.1 (numeraire), Theorem 2.6 (existence)
    - Lemma 3.3, Definition 3.4 (RIPr P* via dP*/dQ = 1/X*), Theorem 3.6 (characterisation)

Safe Testing, P. Grünwald, R. de Heide, W. M. Koolen (2024), JRSS-B - https://arxiv.org/pdf/1906.07801
    - Theorem 1 (the GRO e-variable is the likelihood ratio of Q against the RIPr of Q
      onto the convex hull of the null)

Testing hypotheses generated by constraints, M. Larsson, A. Ramdas, J. Ruf (2025)
    - https://arxiv.org/pdf/2504.02974 (general representation of e-variables for
      constraint-generated hypotheses; the sets below are instances)

Minimax tests and the Neyman-Pearson lemma for capacities, P. J. Huber, V. Strassen (1973),
Annals of Statistics 1(2) 251-263
    - least favourable pairs for epsilon-contamination: the clipped likelihood ratio

Optimal Transport: Old and New, C. Villani (2009), Springer
    - Chapter 6 (Kantorovich-Rubinstein duality: W1 = sup over 1-Lipschitz test functions)

Information geometry and alternating minimization procedures, I. Csiszár, G. Tusnády (1984),
Statistics & Decisions, Supplement 1
    - alternating minimisation for the reverse information projection onto a mixture family

Asymptotically optimal data analysis for rejecting local realism, Y. Zhang, S. Glancy,
E. Knill (2011), Physical Review A 84, 062118
    - prediction-based-ratio test factors for Bell experiments (the polytope instance)

The statistical strength of nonlocality proofs, W. van Dam, R. D. Gill, P. D. Grünwald (2005),
IEEE Transactions on Information Theory 51(8)
    - KL divergence to the local polytope as the optimal growth rate

A composite null is a set P of laws on a finite outcome space of size K.  A nonnegative
vector e is an e-variable for P iff its upper expectation, the support function
sigma_P(e) = sup_{P in P} <P, e>, is at most one.  This module computes sigma_P exactly
for three sets and *certifies* any candidate by e / max(1, sigma_P(e)), so validity is
enforced by computation rather than assumed from a solver's convergence.  Each set's own
duality theory supplies Skeptic's (near) log-optimal strategy against a point belief q:

- ContaminationNull: {(1 - eps) P0 + eps H}.  sigma(e) = (1 - eps) <P0, e> + eps max(e).
  The GRO e-variable is the Huber-Strassen clipped likelihood ratio min(q / P0, c) / Z,
  recovered here by solving the KKT system numerically.
- WassersteinNull: {Q : W1(Q, P0) <= rho}.  sigma is a transport linear programme; by
  Kantorovich-Rubinstein duality any 1-Lipschitz h gives the valid bet
  e = 1 + lam [ (h - <P0, h>) - rho ], and the potential attaining W1(q, P0) from the
  dual LP is Skeptic's direction.  Wealth can grow iff W1(q, P0) > rho.
- PolytopeNull: conv{P_1, ..., P_V}.  sigma(e) = max_v <P_v, e>; the GRO e-variable is
  q / p* with p* the reverse information projection of q onto the hull, computed by
  Csiszár-Tusnády mixture-weight EM.  CHSHLocalRealismNull is the Bell instance.
"""

from abc import ABC, abstractmethod
from typing import Optional, Sequence

import numpy as np
from numpy.typing import NDArray
from pydantic import BaseModel, ConfigDict, Field
from scipy import optimize

from expectation.modules.epower import EPowerCalculator

_DIST_TOL = 1e-9


def _as_distribution(p: NDArray, name: str, *, strictly_positive: bool = False) -> NDArray:
    arr = np.asarray(p, dtype=np.float64).ravel()
    if arr.ndim != 1 or arr.size < 2:
        raise ValueError(f"{name} must be a 1-D array with at least two outcomes")
    if not np.all(np.isfinite(arr)):
        raise ValueError(f"{name} must be finite")
    if np.any(arr < -_DIST_TOL):
        raise ValueError(f"{name} must be nonnegative")
    if abs(arr.sum() - 1.0) > 1e-8:
        raise ValueError(f"{name} must sum to one, got {arr.sum()!r}")
    if strictly_positive and np.any(arr <= 0):
        raise ValueError(f"{name} must be strictly positive on every outcome")
    return np.clip(arr, 0.0, None)


def growth_rate(q: NDArray, e: NDArray) -> float:
    """
    E-power of e under belief q (Ramdas & Wang 2025, Definition 3.11): sum_x q(x) log e(x),
    computed with ``EPowerCalculator`` on the support of q (convention 0 log 0 = 0).
    """
    q = np.asarray(q, dtype=np.float64)
    e = np.asarray(e, dtype=np.float64)
    mask = q > 0
    if np.any(e[mask] <= 0):
        return -np.inf
    return EPowerCalculator().compute(e_values=e[mask], alternative_prob=q[mask]).e_power


class UpperExpectationNull(ABC):
    """A convex set of distributions on ``{0, ..., K-1}`` with an exact support function."""

    def __init__(self, n_outcomes: int):
        if n_outcomes < 2:
            raise ValueError("n_outcomes must be at least 2")
        self.n_outcomes = int(n_outcomes)
        self.last_certificate: Optional[float] = None

    @abstractmethod
    def support_function(self, e: NDArray) -> float:
        """``sup_{P in set} <P, e>`` for a nonnegative vector ``e``."""

    @abstractmethod
    def contains(self, q: NDArray, tol: float = 1e-9) -> bool:
        """Whether ``q`` belongs to the set (up to ``tol``)."""

    @abstractmethod
    def worst_case_member(self, e: NDArray) -> NDArray:
        """A member ``P`` of the set attaining ``sup_P <P, e>`` (the least favourable law)."""

    @abstractmethod
    def _optimal_e_variable(self, q: NDArray) -> NDArray:
        """Uncertified candidate for the log-optimal e-variable against belief ``q``."""

    def certify(self, e: NDArray) -> NDArray:
        """Scale ``e`` down so that its upper expectation is at most one.

        Records the pre-certification upper expectation in ``last_certificate``.
        """
        e = np.asarray(e, dtype=np.float64)
        if e.shape != (self.n_outcomes,):
            raise ValueError(f"e must have shape ({self.n_outcomes},), got {e.shape}")
        if not np.all(np.isfinite(e)) or np.any(e < 0):
            raise ValueError("e must be finite and nonnegative")
        sigma = float(self.support_function(e))
        self.last_certificate = sigma
        if sigma > 1.0:
            return e / sigma
        return e

    def optimal_e_variable(self, q: NDArray) -> NDArray:
        """Certified log-optimal (or near log-optimal) e-variable against belief ``q``.

        Returns the all-ones vector when ``q`` lies in the set: no e-variable can
        then have positive expected log growth under ``q``.
        """
        q = _as_distribution(q, "q")
        if q.shape != (self.n_outcomes,):
            raise ValueError(f"q must have shape ({self.n_outcomes},), got {q.shape}")
        if self.contains(q):
            self.last_certificate = 1.0
            return np.ones(self.n_outcomes)
        return self.certify(self._optimal_e_variable(q))

    def _check_e(self, e: NDArray) -> NDArray:
        e = np.asarray(e, dtype=np.float64).ravel()
        if e.shape != (self.n_outcomes,):
            raise ValueError(f"e must have shape ({self.n_outcomes},), got {e.shape}")
        return e


class ContaminationNull(UpperExpectationNull):
    """Huber's epsilon-contamination neighbourhood ``{(1 - eps) P0 + eps H : H any law}``.

    Parameters
    ----------
    p0 : array_like
        Reference distribution, strictly positive on every outcome.
    epsilon : float
        Contamination fraction in ``[0, 1)``.
    """

    def __init__(self, p0: NDArray, epsilon: float):
        p0 = _as_distribution(p0, "p0", strictly_positive=True)
        super().__init__(len(p0))
        if not 0.0 <= epsilon < 1.0:
            raise ValueError(f"epsilon must be in [0, 1), got {epsilon}")
        self.p0 = p0
        self.epsilon = float(epsilon)

    def support_function(self, e: NDArray) -> float:
        e = self._check_e(e)
        return float((1.0 - self.epsilon) * (self.p0 @ e) + self.epsilon * e.max())

    def contains(self, q: NDArray, tol: float = 1e-9) -> bool:
        q = _as_distribution(q, "q")
        return bool(np.all(q >= (1.0 - self.epsilon) * self.p0 - tol))

    def worst_case_member(self, e: NDArray) -> NDArray:
        e = self._check_e(e)
        H = np.zeros(self.n_outcomes)
        H[int(np.argmax(e))] = 1.0
        return (1.0 - self.epsilon) * self.p0 + self.epsilon * H

    def _kappa_for_cap(self, r: NDArray, m: float) -> float:
        """Solve ``(1-eps) <p0, min(r / kappa, m)> + eps m = 1`` for ``kappa`` (monotone)."""
        target = 1.0 - self.epsilon * m

        def f(log_kappa: float) -> float:
            return float(
                (1.0 - self.epsilon) * self.p0 @ np.minimum(r / np.exp(log_kappa), m) - target
            )

        lo, hi = -50.0, 50.0
        if f(lo) < 0:  # even kappa -> 0 cannot reach the target: cap too small
            return float(np.exp(lo))
        return float(np.exp(optimize.brentq(f, lo, hi, xtol=1e-14, maxiter=500)))

    def _optimal_e_variable(self, q: NDArray) -> NDArray:
        r = q / self.p0
        eps = self.epsilon
        m_max = 1.0 / eps if eps > 0 else float(r.max() / (self.p0 @ r))

        def negative_growth(m: float) -> float:
            kappa = self._kappa_for_cap(r, m)
            return -growth_rate(q, np.minimum(r / kappa, m))

        if eps == 0.0:
            return np.asarray(r, dtype=np.float64)  # plain likelihood ratio
        # Coarse log-grid over the admissible cap, then refine in the best bracket.
        grid = np.exp(np.linspace(np.log(1.0 + 1e-9), np.log(m_max * (1 - 1e-9)), 40))
        values = np.array([negative_growth(m) for m in grid])
        j = int(np.argmin(values))
        lo = grid[max(j - 1, 0)]
        hi = grid[min(j + 1, len(grid) - 1)]
        res = optimize.minimize_scalar(
            negative_growth, bounds=(lo, hi), method="bounded", options={"xatol": 1e-12}
        )
        m_star = float(res.x) if res.fun <= values[j] else float(grid[j])
        kappa = self._kappa_for_cap(r, m_star)
        return np.asarray(np.minimum(r / kappa, m_star), dtype=np.float64)


class WassersteinNull(UpperExpectationNull):
    """Wasserstein-1 ball ``{Q : W1(Q, P0) <= radius}`` on a finite metric space.

    Parameters
    ----------
    p0 : array_like
        Reference distribution, strictly positive on every outcome.
    cost_matrix : array_like, shape (K, K)
        Ground cost; must be symmetric, nonnegative with zero diagonal.  Validity of
        the potential-witness e-variable only needs these properties; equality in
        Kantorovich-Rubinstein duality additionally needs the triangle inequality.
    radius : float
        Ball radius ``rho >= 0``.
    """

    def __init__(self, p0: NDArray, cost_matrix: NDArray, radius: float):
        p0 = _as_distribution(p0, "p0", strictly_positive=True)
        super().__init__(len(p0))
        cost = np.asarray(cost_matrix, dtype=np.float64)
        K = self.n_outcomes
        if cost.shape != (K, K):
            raise ValueError(f"cost_matrix must have shape ({K}, {K}), got {cost.shape}")
        if not np.all(np.isfinite(cost)) or np.any(cost < 0):
            raise ValueError("cost_matrix must be finite and nonnegative")
        if not np.allclose(cost, cost.T):
            raise ValueError("cost_matrix must be symmetric")
        if not np.allclose(np.diag(cost), 0.0):
            raise ValueError("cost_matrix must have a zero diagonal")
        if radius < 0:
            raise ValueError(f"radius must be nonnegative, got {radius}")
        self.p0 = p0
        self.cost = cost
        self.radius = float(radius)
        self._row_sum_matrix = np.kron(np.eye(K), np.ones((1, K)))  # pi -> row sums
        self._col_sum_matrix = np.kron(np.ones((1, K)), np.eye(K))  # pi -> column sums

    # -- linear programmes -------------------------------------------------

    def _support_lp(self, e: NDArray) -> tuple[float, NDArray]:
        K = self.n_outcomes
        # maximise sum_{x,y} pi[x,y] e[y]  s.t. pi >= 0, row sums = p0, <pi, C> <= radius
        c = -np.tile(e, K)
        res = optimize.linprog(
            c,
            A_ub=self.cost.ravel()[None, :],
            b_ub=np.array([self.radius]),
            A_eq=self._row_sum_matrix,
            b_eq=self.p0,
            bounds=(0.0, None),
            method="highs",
        )
        if res.status != 0:
            raise RuntimeError(f"support-function LP failed: {res.message}")
        pi = np.asarray(res.x).reshape(K, K)
        Q = np.clip(pi.sum(axis=0), 0.0, None)
        return float(-res.fun), Q / Q.sum()

    def support_function(self, e: NDArray) -> float:
        e = self._check_e(e)
        return self._support_lp(e)[0]

    def worst_case_member(self, e: NDArray) -> NDArray:
        e = self._check_e(e)
        return self._support_lp(e)[1]

    def wasserstein_distance(self, q: NDArray) -> float:
        """``W1(q, p0)`` by the transport LP."""
        q = _as_distribution(q, "q")
        res = optimize.linprog(
            self.cost.ravel(),
            A_eq=np.vstack([self._row_sum_matrix, self._col_sum_matrix]),
            b_eq=np.concatenate([self.p0, q]),
            bounds=(0.0, None),
            method="highs",
        )
        if res.status != 0:
            raise RuntimeError(f"transport LP failed: {res.message}")
        return float(res.fun)

    def kantorovich_potential(self, q: NDArray) -> NDArray:
        """A 1-Lipschitz ``h`` (w.r.t. the cost) maximising ``<q - p0, h>``.

        Solves the dual LP ``max <q - p0, h>`` s.t. ``h_x - h_y <= C_xy`` for all
        ``x != y`` and ``h_0 = 0`` (the objective is translation invariant).
        """
        q = _as_distribution(q, "q")
        K = self.n_outcomes
        rows = []
        rhs = []
        for x in range(K):
            for y in range(K):
                if x == y:
                    continue
                row = np.zeros(K)
                row[x] = 1.0
                row[y] = -1.0
                rows.append(row)
                rhs.append(self.cost[x, y])
        anchor = np.zeros((1, K))
        anchor[0, 0] = 1.0
        res = optimize.linprog(
            -(q - self.p0),
            A_ub=np.array(rows),
            b_ub=np.array(rhs),
            A_eq=anchor,
            b_eq=np.zeros(1),
            bounds=(None, None),
            method="highs",
        )
        if res.status != 0:
            raise RuntimeError(f"potential LP failed: {res.message}")
        return np.asarray(res.x, dtype=np.float64)

    # -- membership and strategy -------------------------------------------

    def contains(self, q: NDArray, tol: float = 1e-9) -> bool:
        return self.wasserstein_distance(q) <= self.radius + tol

    def witness_e_variable(self, h: NDArray, q: NDArray, radius: Optional[float] = None) -> NDArray:
        """``1 + lam [ (h - <p0, h>) - rho ]`` with ``lam`` log-optimal under ``q``.

        Valid for the whole ball for any 1-Lipschitz ``h`` because
        ``<Q, h> - <p0, h> <= W1(Q, p0) <= rho``.
        """
        rho = self.radius if radius is None else float(radius)
        h = np.asarray(h, dtype=np.float64)
        q = _as_distribution(q, "q")
        # Any Lipschitz violation of h (LP tolerance) is paid as extra tax: for every
        # coupling pi, <Q - p0, h> = sum pi_xy (h_y - h_x) <= sum pi_xy (C_xy + viol).
        viol = float(max(0.0, np.max((h[None, :] - h[:, None]) - self.cost)))
        centred = h - float(self.p0 @ h)
        payoff = centred - rho - viol
        worst = float(payoff.min())
        if worst >= 0:  # cannot happen when p0 > 0 unless h is constant
            return np.ones(self.n_outcomes)
        lam_max = (1.0 - 1e-9) / (-worst)
        if float(q @ payoff) <= 0:
            return np.ones(self.n_outcomes)

        def negative_growth(lam: float) -> float:
            return -growth_rate(q, 1.0 + lam * payoff)

        res = optimize.minimize_scalar(
            negative_growth, bounds=(0.0, lam_max), method="bounded", options={"xatol": 1e-12}
        )
        lam = float(res.x) if res.fun < 0 else 0.0
        return 1.0 + lam * payoff

    def _optimal_e_variable(self, q: NDArray) -> NDArray:
        h = self.kantorovich_potential(q)
        return self.witness_e_variable(h, q)

    def optimal_e_variable(self, q: NDArray) -> NDArray:
        """Potential-witness e-variable against ``q``.

        Valid by Kantorovich-Rubinstein with the Lipschitz-violation tax, so no LP
        certificate is needed; the witness itself returns the trivial bet when the
        dual value ``<q - p0, h>`` does not exceed the radius (in particular whenever
        ``q`` lies in the ball).
        """
        q = _as_distribution(q, "q")
        if q.shape != (self.n_outcomes,):
            raise ValueError(f"q must have shape ({self.n_outcomes},), got {q.shape}")
        e = self._optimal_e_variable(q)
        self.last_certificate = 1.0
        return e


class RIPrResult(BaseModel):
    """Reverse information projection of a belief onto a finite-vertex polytope."""

    model_config = ConfigDict(frozen=True)

    weights: list[float] = Field(description="Mixture weights over the vertices")
    projection: list[float] = Field(description="p* = sum_v w_v P_v")
    kl_divergence: float = Field(ge=0, description="KL(q || p*) in nats")
    n_iterations: int = Field(ge=0)
    converged: bool


class PolytopeNull(UpperExpectationNull):
    """Convex hull of finitely many distributions ``conv{P_1, ..., P_V}``.

    Parameters
    ----------
    vertices : array_like, shape (V, K)
        One distribution per row.  Their supports must jointly cover every
        outcome; otherwise an outcome impossible under the null could occur and
        the plug-in e-variable would be undefined there.
    em_max_iter, em_tol : int, float
        Stopping rule for the mixture-weight EM used in the reverse information
        projection.
    """

    def __init__(
        self,
        vertices: NDArray,
        em_max_iter: int = 2000,
        em_tol: float = 1e-13,
        inside_kl_tol: float = 1e-9,
    ):
        V = np.asarray(vertices, dtype=np.float64)
        if V.ndim != 2 or V.shape[0] < 1:
            raise ValueError("vertices must be a 2-D array with at least one row")
        super().__init__(V.shape[1])
        for v in V:
            _as_distribution(v, "vertex")
        if np.any(V.sum(axis=0) <= 0):
            raise ValueError("vertex supports must jointly cover every outcome")
        self.vertices = np.clip(V, 0.0, None)
        self.em_max_iter = int(em_max_iter)
        self.em_tol = float(em_tol)
        self.inside_kl_tol = float(inside_kl_tol)

    def support_function(self, e: NDArray) -> float:
        e = self._check_e(e)
        return float((self.vertices @ e).max())

    def worst_case_member(self, e: NDArray) -> NDArray:
        e = self._check_e(e)
        return np.asarray(self.vertices[int(np.argmax(self.vertices @ e))], dtype=np.float64)

    def contains(self, q: NDArray, tol: float = 1e-9) -> bool:
        q = _as_distribution(q, "q")
        V = self.vertices.shape[0]
        res = optimize.linprog(
            np.zeros(V),
            A_eq=np.vstack([self.vertices.T, np.ones((1, V))]),
            b_eq=np.concatenate([q, [1.0]]),
            bounds=(0.0, None),
            method="highs",
        )
        if res.status != 0:
            return False
        return bool(np.max(np.abs(res.x @ self.vertices - q)) <= tol)

    def reverse_information_projection(self, q: NDArray) -> RIPrResult:
        """``argmin_{w in simplex} KL(q || sum_v w_v P_v)`` by multiplicative EM updates.

        Each update ``w_v <- w_v <q, P_v / p_w>`` is the Csiszár-Tusnády alternating
        minimisation step for mixture weights and decreases the KL divergence
        monotonically.
        """
        q = _as_distribution(q, "q")
        V = self.vertices.shape[0]
        w = np.ones(V) / V
        mask = q > 0
        P = self.vertices[:, mask]
        qm = q[mask]

        def kl(weights: NDArray) -> float:
            p = weights @ P
            return float(np.sum(qm * np.log(qm / p)))

        current = kl(w)
        converged = False
        n_iter = 0
        for n_iter in range(1, self.em_max_iter + 1):
            p = w @ P
            w = w * (P @ (qm / p))
            w = w / w.sum()
            new = kl(w)
            if abs(current - new) <= self.em_tol * max(1.0, abs(current)):
                current = new
                converged = True
                break
            current = new
        projection = w @ self.vertices
        return RIPrResult(
            weights=w.tolist(),
            projection=projection.tolist(),
            kl_divergence=max(current, 0.0),
            n_iterations=n_iter,
            converged=converged,
        )

    def _optimal_e_variable(self, q: NDArray) -> NDArray:
        ripr = self.reverse_information_projection(q)
        # KL(q || p*) bounds the achievable growth rate; below 1e-9 nats per round the
        # belief is (numerically) in the hull and the trivial bet is the honest answer.
        if ripr.kl_divergence <= self.inside_kl_tol:
            return np.ones(self.n_outcomes)
        p_star = np.asarray(ripr.projection)
        e = np.ones(self.n_outcomes)
        positive = p_star > 0
        e[positive] = q[positive] / p_star[positive]
        return e

    def optimal_e_variable(self, q: NDArray) -> NDArray:
        """Certified numeraire ``q / p*``; membership is read off the projection's KL."""
        q = _as_distribution(q, "q")
        if q.shape != (self.n_outcomes,):
            raise ValueError(f"q must have shape ({self.n_outcomes},), got {q.shape}")
        return self.certify(self._optimal_e_variable(q))


class CHSHLocalRealismNull(PolytopeNull):
    """
    Local realism in a CHSH experiment as a polytope null on the 16 outcomes (a, b, x, y).

    Settings a, b in {0, 1} are drawn with known probabilities pi(a, b); outcomes
    x, y in {0, 1} encode +1, -1.  Local realism (Bell 1964; Clauser, Horne, Shimony & Holt
    1969) makes the conditional outcome law a mixture of the 16 deterministic strategies
    (A(0), A(1), B(0), B(1)), so the joint law of (a, b, x, y) is the convex hull of the
    16 vertex laws P_v(a, b, x, y) = pi(a, b) 1{x = A_v(a)} 1{y = B_v(b)}.

    The certified numeraire against this polytope is the prediction-based-ratio analysis
    of Zhang, Glancy & Knill (2011); its optimal growth rate is the statistical strength of
    van Dam, Gill & Grünwald (2005).  Tsirelson's bound |S| <= 2 sqrt 2 is attained by the
    singlet state at the default angles and serves as the canonical check.

    Parameters
    ----------
    setting_probs : sequence of 4 floats, optional
        pi(a, b) in the order (0,0), (0,1), (1,0), (1,1); default uniform.
    """

    N_OUTCOMES = 16

    def __init__(self, setting_probs: Optional[Sequence[float]] = None, **em_kwargs):
        self.setting_probs = self._setting_probabilities(setting_probs)
        vertices = np.zeros((self.N_OUTCOMES, self.N_OUTCOMES))
        v = 0
        for A0 in (0, 1):
            for A1 in (0, 1):
                for B0 in (0, 1):
                    for B1 in (0, 1):
                        for a in (0, 1):
                            for b in (0, 1):
                                x, y = (A0, A1)[a], (B0, B1)[b]
                                vertices[v, self.outcome_index(a, b, x, y)] = self.setting_probs[
                                    a * 2 + b
                                ]
                        v += 1
        super().__init__(vertices, **em_kwargs)

    @staticmethod
    def _setting_probabilities(setting_probs: Optional[Sequence[float]]) -> NDArray:
        if setting_probs is None:
            return np.full(4, 0.25)
        pi = np.asarray(setting_probs, dtype=np.float64)
        if pi.shape != (4,) or np.any(pi <= 0) or abs(pi.sum() - 1.0) > 1e-9:
            raise ValueError("setting_probs must be four positive numbers summing to one")
        return pi

    @staticmethod
    def outcome_index(a: int, b: int, x: int, y: int) -> int:
        """Index of (a, b, x, y) in the 16-point outcome space (all in {0, 1})."""
        for name, val in (("a", a), ("b", b), ("x", x), ("y", y)):
            if val not in (0, 1):
                raise ValueError(f"{name} must be 0 or 1, got {val}")
        return ((a * 2 + b) * 2 + x) * 2 + y

    def singlet_distribution(
        self,
        angles_a: Sequence[float] = (0.0, np.pi / 2),
        angles_b: Sequence[float] = (np.pi / 4, 3 * np.pi / 4),
    ) -> NDArray:
        """
        Quantum prediction for the singlet state with spin measurements at the given angles:
        P(x, y | a, b) = (1 - s_x s_y cos(theta_a - theta_b)) / 4, s = +1 for outcome 0 and
        -1 for outcome 1.  The default angles attain Tsirelson's bound |S| = 2 sqrt 2.
        """
        q = np.zeros(self.N_OUTCOMES)
        for a in (0, 1):
            for b in (0, 1):
                corr = -np.cos(angles_a[a] - angles_b[b])
                for x in (0, 1):
                    for y in (0, 1):
                        sx = 1.0 if x == 0 else -1.0
                        sy = 1.0 if y == 0 else -1.0
                        q[self.outcome_index(a, b, x, y)] = (
                            self.setting_probs[a * 2 + b] * (1.0 + sx * sy * corr) / 4.0
                        )
        return q

    @classmethod
    def chsh_value(cls, distribution: NDArray) -> float:
        """
        CHSH combination S = E00 - E01 + E10 + E11 of the conditional correlations
        E_ab = E[s_x s_y | a, b]; local realism implies |S| <= 2.
        """
        p = np.asarray(distribution, dtype=np.float64)
        if p.shape != (cls.N_OUTCOMES,):
            raise ValueError(f"distribution must have shape ({cls.N_OUTCOMES},), got {p.shape}")
        corr = np.zeros((2, 2))
        for a in (0, 1):
            for b in (0, 1):
                block = np.array(
                    [[p[cls.outcome_index(a, b, x, y)] for y in (0, 1)] for x in (0, 1)]
                )
                total = block.sum()
                if total <= 0:
                    raise ValueError(f"setting pair ({a}, {b}) has zero probability")
                corr[a, b] = (block[0, 0] + block[1, 1] - block[0, 1] - block[1, 0]) / total
        return float(corr[0, 0] - corr[0, 1] + corr[1, 0] + corr[1, 1])
